// src/lib/smart-transactions-types.ts
// Tipos para o sistema de Transações Inteligentes

import { TransactionCategory } from './types';

// ==================== MERCHANT RULES ====================

/**
 * Regra de estabelecimento - define categoria/carteira padrão para um merchant
 */
export interface MerchantRule {
  id: string;
  userId: string;

  // Identificação do merchant
  merchantName: string; // Nome exato do merchant (para display)
  merchantPatterns: string[]; // Padrões para matching (lowercase, regex patterns)

  // Defaults para transações deste merchant
  defaultCategory: TransactionCategory;
  defaultSubcategory?: string;
  defaultWalletId?: string; // Carteira padrão (opcional)
  defaultType?: 'income' | 'expense'; // Tipo padrão

  // Metadata
  matchCount: number; // Quantas vezes essa regra foi aplicada
  lastMatchedAt?: string; // Última vez que foi aplicada
  createdAt: string;
  updatedAt: string;

  // Flags
  isAutoGenerated: boolean; // Se foi gerada automaticamente pelo sistema
  isActive: boolean; // Se a regra está ativa
}

/**
 * Resultado do matching de uma regra
 */
export interface MerchantRuleMatch {
  rule: MerchantRule;
  confidence: number; // 0-1, quão certa é a correspondência
  matchedPattern: string; // Qual padrão deu match
}

// ==================== RECURRENCE DETECTION ====================

/**
 * Tipos de recorrência detectados
 */
export type RecurrenceFrequency =
  | 'daily'
  | 'weekly'
  | 'biweekly'
  | 'monthly'
  | 'bimonthly'
  | 'quarterly'
  | 'semiannual'
  | 'annual';

/**
 * Transação recorrente detectada pelo sistema
 */
export interface DetectedRecurrence {
  id: string;
  userId: string;

  // Identificação
  pattern: string; // Padrão identificado (ex: "NETFLIX", "SPOTIFY")
  merchantName?: string; // Nome do estabelecimento se identificado

  // Padrão de recorrência
  frequency: RecurrenceFrequency;
  averageAmount: number;
  amountVariation: number; // % de variação aceita

  // Histórico
  lastOccurrence: string; // Data da última ocorrência
  nextExpectedDate?: string; // Próxima data esperada
  occurrences: number; // Número de ocorrências
  transactionIds: string[]; // IDs das transações que formam o padrão

  // Categoria padrão
  category: TransactionCategory;
  subcategory?: string;
  type: 'income' | 'expense';

  // Status
  isConfirmed: boolean; // Usuário confirmou que é recorrente
  isActive: boolean; // Se a recorrência ainda está ativa

  createdAt: string;
  updatedAt: string;
}

// ==================== SMART SUGGESTIONS ====================

/**
 * Sugestão inteligente de categoria
 */
export interface CategorySuggestion {
  category: TransactionCategory;
  subcategory?: string;
  confidence: number; // 0-1
  source: 'merchant_rule' | 'history_pattern' | 'keyword_match' | 'ai';
  reason?: string; // Explicação da sugestão
}

/**
 * Sugestão inteligente de carteira
 */
export interface WalletSuggestion {
  walletId: string;
  walletName: string;
  confidence: number;
  source: 'merchant_rule' | 'history_pattern' | 'category_default';
  reason?: string;
}

/**
 * Conjunto completo de sugestões para uma transação
 */
export interface TransactionSuggestions {
  categories: CategorySuggestion[];
  wallets: WalletSuggestion[];
  isRecurring?: boolean;
  recurrencePattern?: DetectedRecurrence;
  merchantRule?: MerchantRule;
}

// ==================== ANOMALY DETECTION ====================

/**
 * Tipos de anomalias detectadas
 */
export type AnomalyType =
  | 'duplicate' // Transação duplicada
  | 'unusual_amount' // Valor muito diferente do padrão
  | 'unusual_frequency' // Frequência anormal
  | 'missing_recurrence' // Recorrência esperada não apareceu
  | 'new_merchant_high_value'; // Novo estabelecimento com valor alto

/**
 * Alerta de anomalia detectada
 */
export interface TransactionAnomaly {
  id: string;
  userId: string;
  type: AnomalyType;
  severity: 'low' | 'medium' | 'high';

  // Referências
  transactionId: string; // Transação que gerou o alerta
  relatedTransactionIds?: string[]; // Transações relacionadas (para duplicatas)

  // Detalhes
  title: string;
  description: string;

  // Status
  isResolved: boolean;
  resolvedAt?: string;
  resolution?: 'confirmed' | 'ignored' | 'fixed';

  createdAt: string;
}

// ==================== LEARNING DATA ====================

/**
 * Dados de aprendizado do sistema
 * Usado para melhorar sugestões ao longo do tempo
 */
export interface SmartLearningData {
  userId: string;

  // Padrões de palavras-chave por categoria
  keywordPatterns: Record<TransactionCategory, string[]>;

  // Valores médios por categoria
  averageAmountByCategory: Record<TransactionCategory, {
    average: number;
    min: number;
    max: number;
    count: number;
  }>;

  // Carteiras mais usadas por categoria
  walletsByCategory: Record<TransactionCategory, {
    walletId: string;
    count: number;
  }[]>;

  // Horários típicos por tipo de transação
  typicalTransactionTimes: {
    income: { dayOfMonth: number[] }; // Dias típicos de recebimento
    expense: { dayOfWeek: number[] }; // Dias típicos de gastos
  };

  updatedAt: string;
}

// ==================== BULK ACTIONS ====================

/**
 * Ação para aplicar regra a múltiplas transações
 */
export interface BulkRuleApplication {
  ruleId: string;
  transactionIds: string[];
  updateCategory: boolean;
  updateWallet: boolean;
}

/**
 * Resultado da aplicação em lote
 */
export interface BulkActionResult {
  success: boolean;
  updatedCount: number;
  failedCount: number;
  errors?: string[];
}
